### ISSUE TITLE
Table cell colspans

### ISSUE THREAD

**Issue by craigburke** [craigburke/document-builder#12]

**Comment by yellowsnow** [comment]
+1 for this

**Comment by craigburke** [comment]
To simplify the rendering here, I'm going to change how the cell widths are specified (it'll be done at the table level and not at the individual cell level). 

So this is what that will look like:

```
table(columns: [1.inch, 2.inches, 1.inch]) {
    row {
        cell 'Cell1-1'
        cell 'Cell1-2'
        cell 'Cell1-3'
    }
    row {
        cell 'Cell2-1', colspan: 2
        cell 'Cell2-2'
    }
}
```

**Comment by craigburke** [comment]
I think for consistency here I'll change _cell_ to _column_. So here's the proposed new syntax

```
table(columns: [1.inch, 2.inches, 1.inch]) {
    row {
        column 'Column1-1'
        column 'Column1-2'
        column 'Column1-2'
    }
    row {
        column 'Column2-1', colspan: 2
        column 'Column2-2'
    }
}
```

**Comment by yellowsnow** [comment]
What about html syntax? 
 table > tr > td

Pros:
- (Nearly) everybody knows it (i hope for god's sake)
- shorter

Cons:
- Could mislead that all html syntax is supported :)
- Gotta refactor some code :-(

**Comment by craigburke** [comment]
I did originally consider that, but I agree with you that it would probably be confusing for people (especially as I add properties that aren't part of the HTML spec). The refactor itself wouldn't be too bad but that's the real sticking point for me.

**Comment by craigburke** [comment]
After going back and forth I'm going to revert to `cell` instead of `column` I think I'm probably being silly and that the inconsistency would cause confusion for absolutely nobody :smile:

**Comment by yellowsnow** [comment]
There are only two hard things in Computer Science: cache invalidation and
naming things.

-- Phil Karlton

http://martinfowler.com/bliki/TwoHardThings.html

:-D
