### ISSUE TITLE
Tables inside cells

### ISSUE THREAD

**Issue by yellowsnow** [craigburke/document-builder#14]
Motivation : nested tables, also related to #13 and #12 

Cheers

**Comment by craigburke** [comment]
Good call. The way it works now I don't think this should be too difficult. I'll group this in with the 0.5 release but it might end up being part of 0.4 depending on what's involved.

**Comment by yellowsnow** [comment]
Great, thanks!

**Comment by yellowsnow** [comment]
Yess, thanks a lot!

**Comment by craigburke** [comment]
No problem. I'm hoping to wrap things up and release version 0.4 early next week.
