### ISSUE TITLE
Infinite loop issue in PdfDocumentBuilder

### ISSUE THREAD

**Issue by upadhyayap** [craigburke/document-builder#17]
When trying to build complex pdf then sometimes the code keeps running and never returns from onTableComplete closure of PdfDocumentBuilder class.

For more details i have created a gist and a demo code please refer to  
https://gist.github.com/upadhyayap/a351339ba8e8214d5d8c

Demo code can be found here https://github.com/upadhyayap/GdbDemo

**Comment by craigburke** [comment]
Thanks for the example. I'll take a look and try to figure out what's going on.

**Comment by musketyr** [comment]
same here. it's not even complex - there is ten tables and some paragraphs in between.

**Comment by craigburke** [comment]
@musketyr if you're seeing the same issue with the WordBuilder that's helpful information. Must be an issue in the core project.

**Comment by upadhyayap** [comment]
As per my analysis i have figured out some problem at least particular for my case which are mention below,

This problem occurs when we write a component (table,paragraph etc..) in pdf and that component is not getting accommodated  in a single page and there is need to add a page in the pdfdocument.
when a page gets added to the pdf the code forgets that it left something which is not parsed and rendered and onTableComplete closure of PdfDocumentBuilder when we it tries to do tableRenderer.fullyParsed which is a loop breaking condition then due to that we have not changed the fullyParsed flag of the component it never returns true and loop continues forever.
1. In ParagraphRenderer.groovy in parse method    there is code block 

```
while (!reachedEnd) {
            ParagraphLine line = lines[parseStart + linesParsed]
            parsedHeight += line.totalHeight
            linesParsed++

            if (parsedHeight > height) {
                linesParsed = Math.max(0f, linesParsed - 1)
                reachedEnd = true
                fullyParsed = false
            }
            else if (line == lines.last()) {
                reachedEnd = true
                fullyParsed = true
            }
        } 
```

here when parseHeight is greater than supplied height then fullyParsed flag is being set to false and  when a page gets added and height gets incresed then code never comes back and change fullyParsed to true for that particular component which is causing the loop to run infinite times.

For more clarification you can connect with me on skype at **anandupadhyay05** that may help you understand and fix the problem.

**Comment by craigburke** [comment]
@upadhyayap Wow, that's super helpful! 

Yeah, I reworked that whole rendering section of the PdfBuilder recently so I'm not surprised there are edge cases I missed. I'll fix that.

**Comment by upadhyayap** [comment]
I fixed the problem that worked for me now pdf for my case is getting generated successfully.
I have raised a pull request you can review it.
Thank you

**Comment by craigburke** [comment]
I just released 0.4.8 with your PR. Thanks so much for that. I really appreciate it.

**Comment by upadhyayap** [comment]
Thank you so much Craig for releasing the build so quickly. I appreciate that you understood the urgency and worked with me.
keep doing good work , Groovy document builder is awesome Cheers.

**Comment by craigburke** [comment]
I'm glad you're finding it helpful, man. I hope to be able to devote more time to this project soon for an 0.5.0 release :)

**Comment by musketyr** [comment]
Sorry to confuse you the issue were with PDF as well.

Dne út 15. 9. 2015 20:22 uživatel Craig Burke notifications@github.com
napsal:

**Comment by craigburke** [comment]
@musketyr no worries. @upadhyayap was able to resolve it before I even had a chance to pull up the project ;) 

Thanks again to both of you!!
