### ISSUE TITLE
malformed table cells

### ISSUE THREAD

**Issue by musketyr** [craigburke/document-builder#18]
If I run the example from the README file the table is malformed in _LibreOffice: 4.2.8.2 / 420m0(Build:2)_ 

![image](https://cloud.githubusercontent.com/assets/660405/9882156/9aa0e604-5bd3-11e5-9d91-123b064f2527.png)

The text from the cell runs out of the page. I've suspected `tblGrid` section which is missing but adding it didn't make any difference.

The you can find the generated file [here](https://dl.dropboxusercontent.com/u/19383797/1442332588575.docx).

If I upload similar malformed file to Google Drive, on the other hand in preview the cells are narrower but doesn't stretch to 100% either.

![image](https://cloud.githubusercontent.com/assets/660405/9882349/7fe72386-5bd4-11e5-973b-c3722028b4f1.png)

My other suspect is wrong computation of the sizes.

**Comment by craigburke** [comment]
Cool. Thanks for the detailed report. I think your suspicion about computed sizes it right but I'll take a look.

**Comment by musketyr** [comment]
there were a missing type attribute for the widths, see the pull request

**Comment by craigburke** [comment]
Good catch! I really appreciate the PR. I'll release the new version shortly.

**Comment by craigburke** [comment]
0.4.8 was released and includes your PR. Thanks again, man!

**Comment by musketyr** [comment]
Sure thing. Looking forward trying it out tomorrow!

Dne út 15. 9. 2015 20:02 uživatel Craig Burke notifications@github.com
napsal:
