### ISSUE TITLE
Bookmark Support

### ISSUE THREAD

**Issue by musketyr** [craigburke/document-builder#22]
I would be great if the builder has support for bookmarking (see http://officeopenxml.com/WPbookmark.php)

Suggested DSL:

```
paragraph {
    text "Topic", ref: "topic" 
}
paragraph {
    text "This is a "
    text "link to bookmark", href: 'topic'
}
```

**Comment by craigburke** [comment]
I agree. It's on the roadmap for the next version See: #7

**Comment by craigburke** [comment]
There's already a trait for this in the core, just needs to be implemented in both builders:
https://github.com/craigburke/document-builder/blob/master/core/src/main/groovy/com/craigburke/document/core/Linkable.groovy

**Comment by craigburke** [comment]
I'll have to make sure I accommodate links within the document though like your DSL suggests.
