### ISSUE TITLE
Styles don't work. FIX IT!

### ISSUE THREAD

**Issue by craigburke** [craigburke/document-builder#25]
I'm too lazy to type it out, so just look at this tweet:
https://twitter.com/craigburke1/status/652525996139225088

YOU ARE WASTING SO MUCH OF MY TIME WITH YOUR FREE SOFTWARE!! 
:rage: :rage: :rage:

**Comment by craigburke** [comment]
Hi @craigburke. I am so sorry!

Check out version **0.4.13**. The issue of not being able to apply named styles to text elements should be resolved now (thanks for helping me to narrow it down with your helpful issue report).

See the following example:

```
def template = {
    'text.jerk' font: [bold: true, color: '#FF0000', size: 60.pt]
}

builder.create {
    document(template: template) {
        paragraph  {
          text "I hate you, you are a...."
          text "JERK", style:'jerk'
        }
    }
}

```

<img width="765" alt="screen shot 2015-10-09 at 2 08 17 pm" src="https://cloud.githubusercontent.com/assets/793574/10401791/465afc28-6e8f-11e5-80f3-cb9967953867.png">

For your troubles, please accept a 200% refund of the $0 you paid for this software.

**Comment by davydotcom** [comment]
This is a very bipolar repository

**Comment by craigburke** [comment]
@davydotcom you of all people should be able to relate. Don't you submit angry github issues when asset pipeline doesn't work for you? The joys of dogfooding :smile:

**Comment by rpalcolea** [comment]
@craigburke maybe is time to use PHP and https://github.com/hmlb/phpunit-vw you won't regret it

**Comment by craigburke** [comment]
@rpalcolea Awesome! 

I decided to just delete all the tests to help speed up deploy time!!!! :rocket:
