### ISSUE TITLE
Example for Link

### ISSUE THREAD

**Issue by ekretschmann** [craigburke/document-builder#26]
Links seem to be supported but unable to find example in documentation or test cases

**Comment by craigburke** [comment]
Link won't be supported officially until version 0.5 (it currently only works in the Word builder). It's not documented because it's likely to change when 0.5 comes out.

**Comment by ekretschmann** [comment]
I only need it for the Word builder and would be happy refactoring when 0.5 comes out. Could you share an example?

**Comment by craigburke** [comment]
I'm closing this, since I'll add documentation for links when I resolve #7
