### ISSUE TITLE
Multi language support in pdf 

### ISSUE THREAD

**Issue by upadhyayap** [craigburke/document-builder#36]
I am using groovy document builder in my current project and i have requirement to get pdf generated in multi languages like Chinese, Russian,Hindi and in many more languages. Earlier i was not able to do it even by using pdfBox because of  https://issues.apache.org/jira/browse/PDFBOX-922 . But this issue is fixed in pdfBox 2.0.0 which is still in RC. SO do we have any plans for moving to pdfBox 2.0.0

**Comment by upadhyayap** [comment]
i am also not sure how to load external ttf file through GDB. i am doing like below but not working still taking default font settings.
`@groovy.lang.Grab(group='com.craigburke.document', module='pdf', version='0.4.14')
import com.craigburke.document.builder.PdfDocumentBuilder
import com.craigburke.document.core.EmbeddedFont

def pdfgenerator = new PdfDocumentBuilder(new File('multilang_survey.pdf'))
String pwd = System.getProperty("user.dir")

pdfgenerator.create {
    document{
        def font = new EmbeddedFont()
        font.file = new File("$pwd/unifont.ttf")
        font.italic = true
        font.bold = true
        pdfgenerator.addEmbeddedFont(font)
        paragraph(margin: [top: -15.pt]) {
            text "你几岁 - Chinese Simplified"
        }

```
}
```

}
`

**Comment by craigburke** [comment]
@upadhyayap that's definitely the plan. When they do a stable release I'll want to incorporate it. 

I might end up doing it while it's still in RC but I'll have to take a closer look.

**Comment by upadhyayap** [comment]
@craigburke  sure. Meanwhile i have started refactoring the pdf code since i have to meet my project timelines. if you are ok then i can help you in doing that. Let me know when you wanna start.

**Comment by craigburke** [comment]
@upadhyayap this project is still a ways off from a 1.0 release so I have no problem merging a PR that uses the RC version of pdfbox. If the tests still pass I'm good.

I'm focusing on a couple other projects at the moment but if you want to take a crack at it I'd be happy to do a new release.

**Comment by upadhyayap** [comment]
@craigburke raised PR  https://github.com/craigburke/document-builder/pull/40

**Comment by upadhyayap** [comment]
@craigburke is there any release that is going to happen with this PR.

**Comment by craigburke** [comment]
@upadhyayap yeah, the 0.5 release will include this. I just need to wrap up one remaining issue before I release.

**Comment by upadhyayap** [comment]
@craigburke just wanted to check about the release. I have a dependent project which has to get released and the deadline is coming up. I would appreciate your help.

**Comment by upadhyayap** [comment]
@craigburke i understand you have been busy with other projects but if you could find sometime to release it soon that would be great help.

**Comment by craigburke** [comment]
@upadhyayap yeah no problem. One way or another I'll do a release at some point tomorrow.

**Comment by craigburke** [comment]
@upadhyayap give `0.5.0` a spin. Let me know if it works out for you.
