### ISSUE TITLE
Typo in content type

### ISSUE THREAD

**Issue by goeh** [craigburke/document-builder#37]
There is a typo on line 78 in WordDocument.groovy. The content type is prefixed with "conte".
`conteapplication/vnd.openxmlformats-package.core-properties+xml`

https://github.com/craigburke/document-builder/blob/master/word/src/main/groovy/com/craigburke/document/builder/WordDocument.groovy#L78

The interesting thing is that Microsoft Word does not seems to care, it opens documents without complaining.

@craigburke I can create a pull request, but it's so simple so maybe you want to fix it on master?

**Comment by craigburke** [comment]
Lol. Nice catch. I can make the change on master but in general no PR is too small :smile:

**Comment by craigburke** [comment]
This is fixed in master I just forgot to close this when I did it.
