### ISSUE TITLE
trying to use groovy document builder in a grails 2.3.8 app

### ISSUE THREAD

**Issue by ilmoralito** [craigburke/document-builder#41]
I am trying to use groovy document builder in a grails 2.3.8 app but when i try a simple example i get the following error 

URI
    /appName/controllerName/actionName
Class
    java.lang.NoClassDefFoundError
Message
    Could not initialize class com.craigburke.document.core.builder.RenderState

Thanks to https://objectpartners.com/2015/05/14/list-of-groovy-versions-for-each-version-of-grails/ article i got to see that grails 2.3.8 use groovy 2.1.9. This is the same groovy version from grails 2.3.2 until 2.3.11

I tried the same code in a grails 2.4.0 that use groovy 2.3 and groovy document builder works as expected

**Comment by craigburke** [comment]
@ilmoralito ah ok. Yeah, the project relies on Groovy Traits (which were introduced in 2.3), so that's currently the minimum version we need. I should add a note about that in README perhaps.
